# GitHub Actions workflow to automatically test the model after making a new training

name: ML Model Testing

on:
  push:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        id: test
        run: |
          python src/test.py
          echo "::set-output name=accuracy::$(cat accuracy.txt)"
          echo "::set-output name=precision::$(cat precision.txt)"
          echo "::set-output name=recall::$(cat recall.txt)"

  check_accuracy:
    needs: run_tests
    runs-on: ubuntu-latest

    steps:
      - name: Check accuracy
        id: accuracy
        run: |
          accuracy=$(echo "${{ needs.run_tests.outputs.accuracy }}")
          if (( $(echo "$accuracy < 0.94" | bc -l) )); then
            echo "::set-output name=accuracy_pass::false"
          else
            echo "::set-output name=accuracy_pass::true"
          fi

  check_precision:
    needs: run_tests
    runs-on: ubuntu-latest

    steps:
      - name: Check precision
        id: precision
        run: |
          precision=$(echo "${{ needs.run_tests.outputs.precision }}")
          if (( $(echo "$precision < 0.94" | bc -l) )); then
            echo "::set-output name=precision_pass::false"
          else
            echo "::set-output name=precision_pass::true"
          fi

  check_recall:
    needs: run_tests
    runs-on: ubuntu-latest

    steps:
      - name: Check recall
        id: recall
        run: |
          recall=$(echo "${{ needs.run_tests.outputs.recall }}")
          if (( $(echo "$recall < 0.94" | bc -l) )); then
            echo "::set-output name=recall_pass::false"
          else
            echo "::set-output name=recall_pass::true"
          fi

  final_decision:
    needs: [check_accuracy, check_precision, check_recall]
    runs-on: ubuntu-latest

    steps:
      - name: Set final decision
        id: decision
        run: |
          accuracy_pass=$(echo "${{ needs.check_accuracy.outputs.accuracy_pass }}")
          precision_pass=$(echo "${{ needs.check_precision.outputs.precision_pass }}")
          recall_pass=$(echo "${{ needs.check_recall.outputs.recall_pass }}")

          if [[ "$accuracy_pass" == 'true' && "$precision_pass" == 'true' && "$recall_pass" == 'true' ]]; then
            echo "All metrics are above 94%. Accepting the push."
            echo "::set-output name=accept_push::true"
          else
            echo "Metrics are below 94%. Rejecting the push."
            echo "::set-output name=accept_push::false"
          fi
